apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: HEAD
    chart: grafana
  destination:
    server: 'https://4E43FBE6CB81C779E8ACC3930D6C591F.gr7.ap-southeast-2.eks.amazonaws.com'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
