apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: HEAD
    chart: grafana
  destination:
    server: 'https://69F57CC36A5F8E1F0D824F3C960156B9.yl4.ap-southeast-2.eks.amazonaws.com'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
