apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: HEAD
    chart: grafana
  destination:
    server: 'https://2257E12BAC9615FA8A6857B5DF70065B.gr7.ap-southeast-2.eks.amazonaws.com'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
