apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoringtools
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: HEAD
    chart: grafana
  destination:
    server: 'https://FE7ACC37A14E68CCB106DF99CE441948.gr7.ap-southeast-2.eks.amazonaws.com'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
