apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: monitoringtools
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: HEAD
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
  destination:
    server: 'https://FE7ACC37A14E68CCB106DF99CE441948.gr7.ap-southeast-2.eks.amazonaws.com'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
