name: Deploy to EKS

on:
 workflow_dispatch:
      
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
         aws-region: ${{ secrets.REGION }}

    - name: Check for Helm
      id: helm_check
      run: |
        if helm version > /dev/null 2>&1; then
          echo "Helm is already installed"
          echo "helm_installed=true" >> $GITHUB_ENV
        else
          echo "Helm is not installed"
          echo "helm_installed=false" >> $GITHUB_ENV
        fi

    - name: Install Helm
      if: env.helm_installed == 'false'
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Get Bastion Host Public IP
      id: bastion_ip
      run: |
        bastion_ip=$(aws cloudformation describe-stacks --stack-name BastionHostStack --query "Stacks[0].Outputs[?OutputKey=='BastionPublicIP'].OutputValue" --output text)
        echo "::set-output name=ip::$bastion_ip"

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: SSH to Bastion Host and Update Kubeconfig
      env:
        BASTION_IP: ${{ steps.bastion_ip.outputs.ip }}
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$BASTION_IP << EOF
          set -x  # Enable command tracing
          aws eks update-kubeconfig --region ${{ secrets.REGION }} --name MyEKSCluster
          kubectl get nodes
          #Install Argo CLI
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd
          # install helm 
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          sudo chmod 700 get_helm.sh
          ./get_helm.sh
          #Add the Argo CD Helm Repository
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          #Install Argo CD Using Helm
          helm install argocd argo/argo-cd --namespace argocd --create-namespace
          # Wait for argocd-server to be deployed 
          echo "Waiting for argocd-server to be ready..."
          while ! kubectl get deployment argocd-server -n argocd -o jsonpath='{.status.readyReplicas}' | grep -q '1'; do
          echo "argocd-server is not ready yet. Sleeping for 10 seconds..."
          sleep 10
          done
          # expose Argo CD API Server via an AWS Load Balancer, modify the argocd-server service.
          echo "Wait a few minutes for the Load Balancer of Argo CD API Server to provision"
          while ! kubectl patch svc argocd-server -n argocd --type='merge' -p '{"spec": {"type": "LoadBalancer"}}' ; do
          echo "Load Balancer of Argo CD API Server is not ready yet. Sleeping for 10 seconds..."
          sleep 10
          done
          # Get the Load Balancer of Argo CD API Server URL
          kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
          # Access the Argo CD UI and get the password  kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
          # Setting Up Prometheus and Grafana with Argo CD Graph
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
          # Expose Grafana with a Load Balancer
          echo "Wait a few minutes for the Load Balancer of Grafana to provision"
          while ! kubectl patch svc prometheus-grafana -n monitoring --type='merge' -p '{"spec": {"type": "LoadBalancer"}}' ; do
          echo "Load Balancer of Grafana is not ready yet. Sleeping for 10 seconds..."
          sleep 10
          done
          # Get the Grafana Load Balancer URL
          kubectl get svc prometheus-grafana -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
          #Install metrics-server
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          echo "Waiting for metrics-server to be ready..."
          while ! kubectl get deployment metrics-server -n kube-system -o jsonpath='{.status.readyReplicas}' | grep -q '1'; do
          echo "Metrics Server is not ready yet. Sleeping for 10 seconds..."
          sleep 10
          done
          echo "Metrics Server is ready!"
          kubectl top nodes
          kubectl top pods --all-namespaces
          #Enable Argo CD Metrics
          helm upgrade argocd argo/argo-cd --namespace argocd -f values.yaml
          # Open up Argo CD, UI by using Port Forwarding on the ArgoCD service NodePort
          kubectl port-forward service/argocd-server -n argocd 8080:80
          # Use port forwarding to access Prometheus and Grafana
          # Prometheus Dashboard
          kubectl port-forward svc/prometheus-kube-prometheus-prometheus 9090 -n monitoring
          # http://localhost:9090
          # Grafana Dashboard
          kubectl port-forward svc/prometheus-grafana 3000 -n monitoring
          # http://localhost:3000
          # kubectl get secret prometheus-stack-grafana -n monitoring -o jsonpath="{.data.admin-password}" | base64 --decode
        EOF


   # log into localhost:8080 Open a web browser and navigate to http://localhost:8080 Log in with the admin username and the new password you set.
   # Open your browser and go to http://localhost:3000 to access Grafana.
      
